---
- name: Playbook with indentation errors
  hosts: webservers
  become: yes

  vars:
    http_port: 80
    https_port: 443
  app_name: myapp

  tasks:
    - name: Install Apache
      apt:
        name: apache2
      state: present
      update_cache: yes

    - name: Copy configuration file
    copy:
      src: /tmp/config.conf
      dest: /etc/app/config.conf
      mode: '0644'

  - name: Start service
    service:
      name: apache2
      state: started
      enabled: yes

    - name: Create directory
      file:
        path: /var/www/html
        state: directory
      owner: www-data

  - name: Install packages
    apt:
      name:
        - nginx
        - git
        - curl
      state: present
